---
- name: Update packages and reboot
  hosts: all
  become: yes
  tasks:
    - name: Update package cache (Ubuntu)
      apt:
        update_cache: yes
      when: ansible_os_family == 'Debian'

    - name: Update all packages (Ubuntu)
      apt:
        upgrade: yes
        autoremove: yes
        autoclean: yes
      when: ansible_os_family == 'Debian'

    - name: Update package cache (Red Hat/Rocky Linux)
      yum:
        name: '*'
        state: latest
      when: ansible_os_family == 'RedHat' or ansible_distribution == 'Rocky'

    - name: Update all packages (Red Hat/Rocky Linux)
      package:
        name: '*'
        state: latest
      when: ansible_os_family == 'RedHat' or ansible_distribution == 'Rocky'

    - name: Reboot the system
      reboot:
      when: ansible_os_family == 'RedHat' or ansible_os_family == 'Debian'
